//! Generated ANTLR4 lexer and parser for WDL v1.
#![allow(unused_parens)]
//!
//! Files in this module are generated by the ANTLR4 Rust tool from:
//!   wdl-grammar/antlr4/v1/WdlV1Lexer.g4
//!   wdl-grammar/antlr4/v1/WdlV1Parser.g4
//! (consumed via the `rust/antlr4` symlink -> `../wdl-grammar/antlr4`)
//!
//! Post-generation patch: WdlV1ParserParserContext renamed to WdlV1ParserContext.
//! Do not edit these files by hand; run `cargo build` to regenerate.

#[allow(clippy::all)]
pub mod wdlv1lexer;
#[allow(clippy::all)]
pub mod wdlv1parser;
#[allow(clippy::all)]
pub mod wdlv1parserbaselistener;
#[allow(clippy::all)]
pub mod wdlv1parserbasevisitor;
#[allow(clippy::all)]
pub mod wdlv1parserlistener;
#[allow(clippy::all)]
pub mod wdlv1parservisitor;
